---

name: Collect Commit Messages

on: pull_request
permissions:
  pull-requests: write

jobs:
  get-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get commits
        id: get-commits
        run: |
          COMMITS=$(curl  -sL \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "${{ github.event.pull_request.commits_url }}" \
          | jq -r '.[] | "[\(.sha)](\(.html_url)) \(.commit.message)"')
          echo "\n### Automatically added description ###" > ./_commit_messages.txt
          echo "${COMMITS}" >> ./_commit_messages.txt
          
      - name: Update PR Description
        uses: nefrob/pr-description@v1.2.0
        with:
          content: ./_commit_messages.txt
          contentIsFilePath: true
          regex: "### Automatically added description ###\n.*"
          token: ${{ github.token }}        
