---

name: Collect Commit Messages

on: pull_request
permissions:
  pull-requests: read

jobs:
  get-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get commits
        id: get-commits
        run: |
          COMMITS=$(curl  -sL \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "${{ github.event.pull_request.commits_url }}" \
          | jq -r '.[] | "[\(.sha)](\(.html_url)) \(.commit.message)"')
          echo "commits_messages=${COMMITS}" >> GITHUB_ENV
      - name: Print
        run: |
          echo "${{ env.commits_messages }}"
        
