---

name: Collect Commit Messages

on: pull_request
permissions:
  pull-requests: read

jobs:
  get-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get commits
        id: get-commits
        run: |
          curl  -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "${{ github.event.pull_request.commits_url }}"
        
  get-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get commit messages and URLs
      id: get-commits
      uses: actions/github-script@v6
      with:
        script: |
          const prNumber = context.payload.pull_request.number;
          const { data: commits } = await github.pulls.listCommits({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber
          });

          const commitMessagesAndUrls = commits.map(commit => ({
            message: commit.commit.message,
            url: commit.html_url
          }));

          return commitMessagesAndUrls;

    - name: Output commit messages and URLs
      run: |
        echo "Commit messages and URLs:"
        echo "${{ steps.get-commits.outputs.result }}"
